### ISSUE TITLE
Support for video?

### ISSUE THREAD

**Issue by rosskimes** [jaredsinclair/JTSImageViewController#19]
Any plans or interest in using this controller for video as well as images? If so, I would be happy to work on it (I just don't want to put the work in if you don't have any interest of supporting video at all).

**Comment by larcus94** [comment]
@rosskimes, @kbala, @BObereder I made a [fork](https://github.com/larcus94/JTSImageViewController) that has a basic video support.

**Comment by kbala** [comment]
Oh good. Let me test

**Comment by happiehappie** [comment]
Just wondering, is this being worked on at the moment???
