### ISSUE TITLE
Why does not support multiple picture scroll?

### ISSUE THREAD

**Issue by isaced** [jaredsinclair/JTSImageViewController#23]

**Comment by rounak** [comment]
I am also looking forward to the addition of this feature.

**Comment by alvintchui** [comment]
would be very useful to have this enhancement done

**Comment by makartraktor** [comment]
me too!

**Comment by mluisbrown** [comment]
If you used the component you would understand why. What gesture would you use to scroll to the next image? A single touch pan is already used to flick / slide the image away. The use case for this control is clearly for viewing a single image at a time and then flicking it away to go back to where you were.

**Comment by rounak** [comment]
@mluisbrown Vertical gestured could be used to dismiss, and horizontal gestures could be used to page between images.

**Comment by isaced** [comment]
+1, Just like [IDMPhotoBrowser](https://github.com/ideaismobile/IDMPhotoBrowser).

**Comment by mluisbrown** [comment]
@isaced and @rounak have either of you played with JTSImageViewController? Either in the sample app or in the [Unread](https://itunes.apple.com/us/app/unread-rss-news-reader/id911364254?mt=8) app (originally created by Jared Sinclair)? Have you ever used a similar control in Tweetbot for iOS?

If you had, you would understand why there is no gesture that could be used for swiping between multiple images. The whole *point* of this control is for viewing a **single** image and being able to dismiss it by flicking it in **any** direction.

If you would like an image viewer that supports multiple images, there are plenty of others out there.

**Comment by inb4ohnoes** [comment]
I think if you had used Tweetbot like you said yourself, you would have seen that Tweetbot has multiple image support just like everybody here is requesting. Please check your facts before berating other people.

**Comment by mluisbrown** [comment]
@inb4ohnoes my bad, Tweetbot (which I use every day btw) does have multiple image support. They have done it by using the horizontal pan gesture, which significantly reduces the 'flickability' of the image to dismiss it, all though I guess it's a necessary compromise in that case. JTSImageViewController was created for Unread.app, where the use case is/was specifically single image viewing.
