### ISSUE TITLE
Flickering (zoom / dismiss conflict) + make fick to dismiss an option

### ISSUE THREAD

**Issue by andrew-frank** [jaredsinclair/JTSImageViewController#37]
On a real device, when I want to zoom the image, it flickers (actually really fast resizes/moves), whenever my zoom gesture is fast. I have to zoom very gently to prevent this. Once I manage to zoom it's ok, this issue appears for zoomLevel == 1 and fast gesture.

On simulator it happens if I firstly drag it with mouse, then press option, to begin zooming, when I firstly click option, than mouse, it's ok. So probably it recognizes the beginning of zooming as dragging.

Here's a gif:

![](http://gifyu.com/images/Untitled05fc6.gif)

(this is iOS 7.1 with JTS 1.3, although I did notice this issue a month ago, when I firstly tried to use it)
The example works fine, the problem is with presenting it from my tableViewCell.

I tried with different combinations of referenceRect/View and modifying code in library (messing with _flags and zoomLevel), but with no luck.

What I do is add a UITapGestureRecognizer to my UIImageView in a UITableViewCell. In tap handler I present JTS:

``` objective-c

//Note: This happens in UITableViewCell subclass

-(void)awakeFromNib
{
self.photoImageView.userInteractionEnabled = YES;
    UITapGestureRecognizer *imageTapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleTap:)];
    [self.photoImageView addGestureRecognizer:imageTapGesture];
}

-(void)handleTap:(UITapGestureRecognizer *)gesture
{
    CGPoint location = [gesture locationInView:[gesture.view superview]];
    if(!CGRectContainsPoint(self.photoImageView.frame, location))
        return;

    JTSImageInfo *imageInfo = [JTSImageInfo new];
    imageInfo.image = self.photoImageView.image;
    imageInfo.referenceRect = self.photoImageView.frame;
    imageInfo.referenceView = self.parentVC.view;

    JTSImageViewController *imageViewer = [[JTSImageViewController alloc] initWithImageInfo:imageInfo mode:JTSImageViewControllerMode_Image backgroundStyle:JTSImageViewControllerBackgroundStyle_ScaledDimmedBlurred];

    imageViewer.interactionsDelegate = self; //thought I could block flickering this way, but tapping also has been disabled
    imageViewer.dismissalDelegate = self;

    [imageViewer showFromViewController:self.parentVC transition:JTSImageViewControllerTransition_FromOffscreen]; //transition has no impact on this issue
}
```

**Comment by bigbadleroybrown** [comment]
Hey @frandrzej looks like you were doing something similar to what I've got going on. If you have a second I'd love to ask you a quick question about how you implemented this library with UIImageView inside of Tableview cell.

Thanks!

**Comment by frandrzej** [comment]
Hi @bigbadleroybrown. I had no luck here (as of version 1.3), so I ended up using https://github.com/ideaismobile/IDMPhotoBrowser
