### ISSUE TITLE
Jerking motion on initial transition on iPhone 6 and 6+

### ISSUE THREAD

**Issue by edekhayser** [jaredsinclair/JTSImageViewController#39]
When presenting images, such as the one in the sample project, on the iPhone 6 and 6+ simulators, the main view seems to jerk before presenting the image. It enlarges a little, then shrinks back, then continues with the correct animation.

**Comment by civilordergone** [comment]
It's still present w/ the latest build...

**Comment by edekhayser** [comment]
Sorry I have not resolved this sooner. I will not have time to find the root of the problem until school ends on the 18th. 

If you happen to fix the bug, please fork and file a pull request so it can be fixed.

**Comment by civilordergone** [comment]
It's weird because the issue isn't consistent.  When presenting the
jtsimageviewer modal, it might appear to load properly on the 5th click or
the 12th...

Ok
