### ISSUE TITLE
JTSImageViewControllerBackgroundStyle_ScaledDimmed does not exist

### ISSUE THREAD

**Issue by mythodeia** [jaredsinclair/JTSImageViewController#41]
in your demo project there is an error in the ```JTSViewController.m``` file
The ```JTSImageViewControllerBackgroundStyle_ScaledDimmed``` backgroundStyle does not exist in the JTSImageViewControllerBackgroundOptions NS_OPTIONS

Plus there is another occurence in ```JTSViewController.m``` line 159

thanks for the lib

**Comment by seanhealy** [comment]
I'm also seeing this same issue. Just looking through older versions to see if it was lost somewhere.

**Comment by mythodeia** [comment]
@jaredsinclair any updates on this?
