### ISSUE TITLE
view is not in the window hierarchy!

### ISSUE THREAD

**Issue by bluekite2000** [jaredsinclair/JTSImageViewController#43]
After I added 2 new viewcontrollers A and B before C (which is where timeline is added) I get 
Warning: Attempt to present <JTSImageViewController: 0x137083c00> on <UIViewController: 0x136e0d130> whose view is not in the window hierarchy!

My question is in line 
	imageViewer!.showFromViewController(UIApplication.sharedApplication().keyWindow?.rootViewController, transition: JTSImageViewControllerTransition._FromOriginalPosition) 

I need to replace UIApplication.sharedApplication().keyWindow?.rootViewController with sth in order to access C. What to do?

**Comment by jevonszmx** [comment]
same warning.

I try to addGestureRecognizer to imageview in UItableViewCell，it woks fine，but i get this warning。

**Comment by jevonszmx** [comment]
Fixed!

Reason:

http://stackoverflow.com/questions/26022756/warning-attempt-to-present-on-whose-view-is-not-in-the-window-hierarchy-sw

so I try to change my code like this:

```
    JTSImageInfo *imageInfo = [[JTSImageInfo alloc] init];
    imageInfo.imageURL = [NSURL URLWithString:pic.imageurl];
    imageInfo.referenceRect = self.tableView.frame;
    imageInfo.referenceView = self.tableView.superview;
```

the 'referenceView' is very important!!

**Comment by MuscleRumble** [comment]
I had this issue, too... with `UILongPressGestureRecognizer` on a `UICollectionViewCell`. But that was totally fine, because the gesture recognizer event is called twice.

Check for this `if (gesture.state == UIGestureRecognizerStateBegan)` and `UIGestureRecognizerStateEnded ` should be ignored.
