### ISSUE TITLE
Issue if imageview frame is different upon dismissal

### ISSUE THREAD

**Issue by mommyme** [jaredsinclair/JTSImageViewController#44]
This is more of a comment on functionality, but if the frame of the source imageView is in a different place upon dismissal than it was upon presentation (i.e. if presented when containing scrollview is pulled down, and has returned to normal position by dismissal), there are some choppy animation issues. A possible enhancement would be to give the ability to specify imageInfo for the imageView state upon dismissal as well as upon presentation.

**Comment by jaredsinclair** [comment]
This is a good suggestion.

**Comment by mommyme** [comment]
I'm a very novice programmer so I have no idea how to do this, or I would do it myself. Sorry, because I do still think it would be a super useful enhancement.
