### ISSUE TITLE
Crash Upon Dismissal

### ISSUE THREAD

**Issue by nmock** [jaredsinclair/JTSImageViewController#45]
Not really sure what I'm doing wrong, but couldn't find anybody having the same issues. I'm presenting the image controller as described in the README. Getting several different crashes, always when dismissing the image.

        UIViewController *vcToShowFrom = ((AppDelegate*)[[UIApplication sharedApplication] delegate]).mainNavigationController.visibleViewController;
        
        JTSImageInfo *imageInfo = [[JTSImageInfo alloc] init];
        imageInfo.imageURL = url;
        imageInfo.referenceRect = vcToShowFrom.view.bounds;
        imageInfo.referenceView = vcToShowFrom.view;
        
        JTSImageViewController *imageViewer = [[JTSImageViewController alloc]
                                               initWithImageInfo:imageInfo
                                               mode:JTSImageViewControllerMode_Image
                                               backgroundStyle:JTSImageViewControllerBackgroundOption_None];
        
        [imageViewer showFromViewController:vcToShowFrom transition:JTSImageViewControllerTransition_FromOriginalPosition];```

Crash 1:
```-[UITransitionView didAddSubview:]: message sent to deallocated instance 0x15f671e40```

Crash 2:
```[CATransaction synchronize] called within transaction```

**Comment by hashitha** [comment]
I had the same issue and it appear to happen when i calculated tableviewcell height from an attributed string in heightForRowAtIndexPath. i fixed this by caching the heights when it first loads.

**Comment by nmock** [comment]
Thanks! That fixed the problem!
