### ISSUE TITLE
Image Doesn't appear from screen bounds / Unresponsive Zoom

### ISSUE THREAD

**Issue by nmock** [jaredsinclair/JTSImageViewController#47]
When I try to launch the image viewer, it zooms from outside of the screen into place. Also, whenever I interact with the image, it is extremely finicky and won't retain zoom position until a bunch of attempts are made. Attached a video of the issue. https://www.dropbox.com/s/c3thknvpagzk5nf/IMG_0044.MOV?dl=0

    JTSImageInfo *imageInfo = [[JTSImageInfo alloc] init];
    imageInfo.imageURL = url;
    //            imageInfo.referenceRect = vcToShowFrom.view.bounds;
    //            imageInfo.referenceView = vcToShowFrom.view.superview;
            
    JTSImageViewController *imageViewer = [[JTSImageViewController alloc]
                                                   initWithImageInfo:imageInfo
                                                   mode:JTSImageViewControllerMode_Image
                                                   backgroundStyle:JTSImageViewControllerBackgroundOption_None];
            
    [imageViewer showFromViewController:vcToShowFrom transition:JTSImageViewControllerTransition_FromOriginalPosition];

**Comment by jaredsinclair** [comment]
Are you providing the imageInfo with an `image` or a `placeholderImage` property before initializing the viewer?
