### ISSUE TITLE
Add actionView for having custom actions like retweeting, liking et cetera.

### ISSUE THREAD

**Issue by jarimartens10** [jaredsinclair/JTSImageViewController#50]
Hi, could you add a ```UIView actionView``` or ```Array<UIButton> actionButtons``` to JTSImageViewController. It could come in handy for downloading, mailing, retweeting, liking et cetera

**Comment by jaredsinclair** [comment]
This delegate: https://github.com/jaredsinclair/JTSImageViewController/blob/master/Source/JTSImageViewController.h#L217
