### ISSUE TITLE
there is a serious bug in this code. show  someone GIF images will crash ,there some info about this problem

### ISSUE THREAD

**Issue by 12207480** [jaredsinclair/JTSImageViewController#55]
![image](https://cloud.githubusercontent.com/assets/6346030/6591984/a2a09526-c802-11e4-9232-a3428401f49a.png)
gif   url:   http://www.233.com/NewsFiles/2015-3/11/111/111.gif  

I hope you can solve this problem as soon as possible，thank you very much.

**Comment by jaredsinclair** [comment]
@12207480 Thanks for the reproducible test case. Fixed! :-)
