### ISSUE TITLE
Swift compatibility

### ISSUE THREAD

**Issue by Urkman** [jaredsinclair/JTSImageViewController#57]
How is the compatibility to use this library in a Swift project?

**Comment by jaredsinclair** [comment]
You can use this in a project that also uses Swift.

– Jared Sinclair

**Comment by IsaiahJTurner** [comment]
I can't seem to get it to work either. Using CocoaPods I added `#import "JTSImageViewController/JTSImageViewController.h"` to my bridging header but I can't create an `JTSImageInfo` object in a Swift class.

**Comment by odedharth** [comment]
Also had problems linking the files...

**Comment by mrojas** [comment]
@IsaiahJTurner you have to `import JTSImageViewController` in your swift class

**Comment by Elgins** [comment]
@mrojas I add source code into my Swift project but I can not even import JTSImageViewController and I am sure I have add the riding file and added the#import "JTSImageViewController/JTSImageViewController.h", do u have any idea how can I import JTSImageViewController? Many this if u could help me.
