### ISSUE TITLE
Expose scrollView.maximumZoomScale as a settable property

### ISSUE THREAD

**Issue by ryanio** [jaredsinclair/JTSImageViewController#62]
I'd love if scrollView.maximumZoomScale was a settable property when initializing JTSImageViewController: https://github.com/jaredsinclair/JTSImageViewController/blob/85de5b67302dc80f63d1a39355dff8384aab839e/Source/JTSImageViewController.m#L437

The hardcoded value of 8.0 is really high, and allows people to zoom in to a very grainy level. I'm personally setting it to 2.0

**Comment by seanhealy** [comment]
+1 Would love to see this.
