### ISSUE TITLE
Background flickers w/ iPhone 6 when clicking image

### ISSUE THREAD

**Issue by civilordergone** [jaredsinclair/JTSImageViewController#65]
It looks like the size of cloned UIView gets shifted (the title moves down then flickers away)..  Is it possible to just have a complete black overlay then have the image do the animation expand into its placeholder to avoid showing the existing UIView?  

This is preventing me from using this tool in production.

**Comment by civilordergone** [comment]
It's occurring on my iPhone 6.  It appears to work properly on an iPhone 4s. :|

**Comment by civilordergone** [comment]
It's supporting devices running on iOS 7 too btw..

**Comment by pushtheworldllc** [comment]
Yeah i'm seeing this as well any fix?

**Comment by jaredsinclair** [comment]
It sounds like your Xcode app target isn't configured to support the iPhone 6. If you're not using a launch storyboard you'll have to include the appropriate launch images to get native support for iPhone 6 and 6 Plus.

**Comment by civilordergone** [comment]
@jaredsinclair by adding the appropriate launch images, it'll get this project to work properly on the iPhone 6?

**Comment by civilordergone** [comment]
For launch images, I'm selecting "iOS 7.0 and Later - iPhone Portrait", do you mean I should select iOS 8 and later iphone portrait as well?

**Comment by civilordergone** [comment]
Okay, just added a launch storyboard and it added iPhone 6 support, thanks
