### ISSUE TITLE
Complilation error and UIKit

### ISSUE THREAD

**Issue by seland** [jaredsinclair/JTSImageViewController#66]
I try compiling project with JTSImageViewController pod and without .pch file, that includes #import <UIKit/UIKit.h> and I have a lot of compilation error because of unknown types like UIImage, CGRect and so on.

**Comment by arturkyulyan** [comment]
Click on your target, go to Build Settings, in the search box put "Enable Modules" and switch the flag from NO to YES. Compile again. Hope this will help.
