### ISSUE TITLE
Background Rotation

### ISSUE THREAD

**Issue by Hackmodford** [jaredsinclair/JTSImageViewController#67]
I noticed that the view controller that is beneath the image does not rotate. This means if you display an image, then rotate the screen, then dismiss the image. There is an abrupt change in orientation after the animation finishes. Is there a way for the view beneath the image to rotate also?

**Comment by knt** [comment]
I'm facing the same issue as well. Did you ever find a workaround?

**Comment by Hackmodford** [comment]
No, I ended up not using it. I didn't come up with an alternative either.

**Comment by bmoliveira** [comment]
I have the same issue as well, anyone found a solution or an alternative?

**Comment by siberianisaev** [comment]
``` swift
extension MyController : JTSImageViewControllerDismissalDelegate {
    
    func imageViewerDidDismiss(imageViewer: JTSImageViewController!) {
        // handle orientation did change
    }
    
}
```
