### ISSUE TITLE
Didn't find 1.5 on cocoapods.org?

### ISSUE THREAD

**Issue by jiayuzhang** [jaredsinclair/JTSImageViewController#68]
![image](https://cloud.githubusercontent.com/assets/1060974/8398516/6ecb1484-1dbf-11e5-8d4b-accea7e8e628.png)

**Comment by isaced** [comment]
+1

**Comment by dlo** [comment]
Yep. Looks like 1.5 hasn't been pushed to Cocoapods. @jaredsinclair could you do us all a solid and `pod trunk push`? :sparkles:

**Comment by jaredsinclair** [comment]
Bah, thanks, will do.

**Comment by jaredsinclair** [comment]
Okay, cool. The latest is now `1.5.1`, too.
