### ISSUE TITLE
It has an error In Swift project

### ISSUE THREAD

**Issue by Heisenbean** [jaredsinclair/JTSImageViewController#74]
![image](https://cloud.githubusercontent.com/assets/7660120/9158819/b9b255be-3f4f-11e5-9d95-668ca3f9b4da.png)

sorry to bother u,it's a simple error
`@import UIKit;`,then the 'JTSImageInfo.h' file will get the same error too,just `@import UIKit;`in the 'JTSImageInfo.h'  will solve this error.

**Comment by mehulparmar4ever** [comment]
Same issue i am facing while using this library in Swift, Can anyone please help me. !!??
