### ISSUE TITLE
Any guide to use in swift, for a newbie? 

### ISSUE THREAD

**Issue by jasan-s** [jaredsinclair/JTSImageViewController#75]
Also can this be implemented so the enlarged image is only shows for the time the user finger is on the screen? And if I have another photo can the user swipe to see the other pic in the enlarged mode?

**Comment by matrpedreira** [comment]
This is how I'm using the code from ReadMe on my code in swift.
@IBAction func openImage(sender: UIButton) {
        let imageInfo = JTSImageInfo()
        imageInfo.image = profileUser.profilePic
        imageInfo.referenceRect = sender.frame
        imageInfo.referenceView = sender.superview
        let imageViewer = JTSImageViewController(imageInfo: imageInfo, mode: JTSImageViewControllerMode.Image, backgroundStyle: JTSImageViewControllerBackgroundOptions.Scaled)
        imageViewer.showFromViewController(self, transition: JTSImageViewControllerTransition._FromOriginalPosition)
    }

**Comment by StevenTso** [comment]
the only thing I would change is for the last line:

`imageViewer.showFromViewController(self, transition: JTSImageViewControllerTransition.FromOriginalPosition)`
