### ISSUE TITLE
Feature request: flick to dismiss like Facebook

### ISSUE THREAD

**Issue by UberJason** [jaredsinclair/JTSImageViewController#80]
Hi Jared,

I love this library, it's incredibly easy to use as a developer and fun to use as a user!

I wonder if you'd consider for a future release adding a Facebook-style flick-to-dismiss animation, rather than just the Tweetbot flick-to-dismiss animations. In this style, when you flick the image, it moves briefly in the direction you've flicked it, then with a rubber-band animation, it moves and scales into the final image position. You already use this animation when the user taps to dismiss the photo, so it seems like it wouldn't be too much more effort for you to add this as a flick-to-dismiss animation.

**Comment by akhilcb** [comment]
This is a great library. Any plans to have the above mentioned feature added to it?
