### ISSUE TITLE
setStatusBarHidden:withAnimation:' is deprecated 

### ISSUE THREAD

**Issue by vargarobert** [jaredsinclair/JTSImageViewController#82]
'setStatusBarHidden:withAnimation:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController prefersStatusBarHidden]

**Comment by myusuf08** [comment]
how to solve this?

**Comment by jaredsinclair** [comment]
That’s in there for legacy reasons. At the time I created JTSImageviewController, not every app was using the modern style. In the future I will remove these references but there's no reason to do so hastily. Your app can use `prefersStatusBarHidden` in all your view controllers and things will "just work."
