### ISSUE TITLE
iOS 9 setStatusBarHidden is deprecated

### ISSUE THREAD

**Issue by mbachrach** [jaredsinclair/JTSImageViewController#84]
under iOS 9, this warning appears several times during compilation:  
'setStatusBarHidden:withAnimation:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController prefersStatusBarHidden]

It's not difficult to fix per se (the correct approach has been around since iOS 7), but because it doesn't appear that iOS 9 provides a means of animating the status bar fade--you've either got it or not--changing this will affect the logic a bit.

**Comment by UberJason** [comment]
Seconding this fix (would love to get rid of those warnings), but also a link to a StackOverflow that shows that you can still animate the status bar change: http://stackoverflow.com/questions/32808593/setstatusbarhidden-withanimation-deprecated-in-ios-9

**Comment by shagedorn** [comment]
This PR fixes the warnings if you only support iOS 9 and up, while still allowing you to use the deprecated model in case you must support earlier versions:
https://github.com/jaredsinclair/JTSImageViewController/pull/101
