### ISSUE TITLE
why not allow call updateInterfaceWithImage

### ISSUE THREAD

**Issue by Marindrew** [jaredsinclair/JTSImageViewController#87]
Dear @jaredsinclair , thank you for such a great library!

Why not making - (void)updateInterfaceWithImage:(UIImage *)image a public method?

I open preview and then download the picture and save in cache (I know the library can download the image but it'll not save it in my developed cache).

So I was surprised I cannot change the picture after showFromViewController is called.

Sorry if I didn't understand something.

**Comment by tomlerendu** [comment]
@Marindrew I am having the same issue as you described. Did you ever find a work around for this?
