### ISSUE TITLE
Blurry Image when Image is smaller than image view

### ISSUE THREAD

**Issue by mommyme** [jaredsinclair/JTSImageViewController#89]
I may be missing something, but I have a problem when an image is smaller than the image view it is being displayed in. This is mostly an issue on the iPad. The image is stretched to fill the entire image view instead of just being displayed smaller (and at a suitable resolution) within the image view. I feel like I must be missing something, but if not, this may be a bug, or at least an intended effect?

**Comment by fysteven** [comment]
Hey mommyme, you might want to check if you have a larger image. If you used a larger one, which is larger or exactly the same as the image view, you'd get an image with very good quality.

**Comment by mommyme** [comment]
The issue is that it is a user-supplied image. The user is able to select their own images, and an image may be smaller than the imageview size. In this case, I would hope that JTSImageViewController would resize the imageview or at least change its content mode accordingly. Not everything is controllable by the developer and often with images it is the case that image sizes are not under strict developer control so that the user can choose images appropriate to their task. While it is easier to enforce a max image size by resizing a large image, I personally do not find it user friendly to enforce a min image size, as the user doesn't even always control the image size themselves but may be showing an image from the web, etc. I just think it is always a good idea to handle each case scenario, this being an important one.

**Comment by fysteven** [comment]
Ok. I got what you mean. It makes sense to not scale a small image on the screen.
