### ISSUE TITLE
A problem while showing from a UIImageView with content mode: AspectFit

### ISSUE THREAD

**Issue by andrehen** [jaredsinclair/JTSImageViewController#90]
Hi,
First, this is some really good work You've done here jaredsinclair.

I'm having a problem showing images taken in Portrait and showing then from a UIImageView, with the Transition_FromOriginalPosition. The problem is that the animation begin from inside the image, not from the current image itself. The problem only happen is the content mode is set to AspectFit. I've made a video to demonstrate the effect happening and the difference between Aspect Fit and Aspect Fill:  

https://dl.dropboxusercontent.com/u/385021/JTSImageVC_AspectFit.mov

It happened with images taken from a iPhone 6S Plus and a iPhone 5S.

Here is the image I used:

https://dl.dropboxusercontent.com/u/385021/IMG_0332.JPG

**Comment by senseluo** [comment]
I have the same issue
