### ISSUE TITLE
What if I wanna save the image into Local Album? 

### ISSUE THREAD

**Issue by rydensun** [jaredsinclair/JTSImageViewController#98]
Like long-pressing or add a button at the left/right corner?

**Comment by martins-p-sergio** [comment]
Just register for _JTSImageViewControllerInteractionsDelegate_ and listen to
_- (void)imageViewerDidLongPress:(JTSImageViewController *)imageViewer atRect:(CGRect)rect;_
Simply retrieve the image _[imageViewer image]_ and process / save it as needed.

To add buttons, you could subclass _JTSImageViewController_ with a custom xib and then simply add the buttons you need, or do it directly in code.
